### ISSUE TITLE
При использовании метода join появляется сообщение, что потеряна связь с интернетом

### ISSUE THREAD

**Issue by AllohaSnackBar** [pythontutor/pythontutor-ru#90]

**Comment by yourconscience** [comment]
Не совсем так.
На самом деле, неправильно обрабатывается код, в котором join получает аргументы типа, отличного от str.
Например, такой код: 
print(''.join([int() for _ in input().split()]))
Вместо TypeError возникает упомянутое сообщение о потери связи с интернетом.

**Comment by vpavlenko** [comment]
```
ERROR 2015-10-23 22:23:16,782 Internal Server Error: /visualizer/execute/
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/srv/production/pythontutor/tutorial/views/visualizer.py", line 49, in execute
    explain_error(event, user_script)
  File "/srv/production/pythontutor/tutorial/views/visualizer.py", line 27, in explain_error
    exc['exception_translation'] = translate_error(msg, line)
  File "/srv/production/pythontutor/errors/error_translations.py", line 465, in translate_error
    explanation = error.get_translation(error_msg)
  File "/srv/production/pythontutor/errors/error_translations.py", line 32, in get_translation
    return self.translation.format(*re.match(self.regexp, error_msg).groups())
IndexError: tuple index out of range
```
